/**
 * The sequence of messages one reading produces (RF-17, D-04).
 *
 * It used to live inside the provider, where it could only be exercised with
 * the editor nearby. Here it is a pure function: roots and a reader in, the
 * envelopes in order out, plus the root that ended up observed. Nothing in it
 * knows about webviews, views or disposables.
 *
 * The provider stays the owner of sending, of visibility and of opening a
 * file, because all three depend on the editor. What moved is only the rule of
 * which message goes out in what order — and that rule now has a second
 * consumer, the preview of feature 005, which serves the panel outside the
 * editor. Two hosts, one sequence.
 * @module host/session
 */

import { INHERITED_MODEL_REVISION } from './inheritance.ts'
import type { HostMessage } from './protocol.ts'
import type { ReadingResult } from './reading.ts'
import { chooseRoot } from './root.ts'

/**
 * What this build knows about itself, handed in rather than imported.
 *
 * It arrives as a PARAMETER, and `inheritance.ts` does not, and the asymmetry
 * is deliberate: the inherited revision is versioned and therefore always on
 * disk, whereas the build stamp is generated by every build and deliberately
 * NOT versioned (D-19). A module that imported it would stop compiling in a
 * fresh clone before the first build — and this one has a second consumer, the
 * preview, which has its own way of knowing what it is running.
 */
export interface BuildStamp {
  /** The derived version of this build. */
  version: string
  /** The commit it was made from, whole. */
  commit: string
}

/**
 * What a caller that knows nothing about the build sends instead.
 *
 * Empty rather than invented: the header draws "não declarado" for an empty
 * value, which is the truthful thing to say, and a plausible-looking number
 * would be indistinguishable from a real one.
 */
const UNSTAMPED: BuildStamp = { version: '', commit: '' }

/** The envelopes of one reading, and the root they came from. */
export interface SessionSequence {
  /** In order, starting with the loading state the panel depends on. */
  messages: HostMessage[]
  /** The observed root, or null when there is no folder at all. */
  observedRoot: string | null
}

/**
 * Build the sequence of one reading.
 * @param roots - every workspace root, in the editor's order.
 * @param read - reads one root; called at most once per root.
 * @param build - what this build knows about itself (RF-17).
 * @returns the envelopes in order, and the observed root.
 */
export function sessionMessages(
  roots: readonly string[],
  read: (root: string) => ReadingResult,
  build: BuildStamp = UNSTAMPED,
): SessionSequence {
  // The loading state opens every sequence, before any disk is touched: the
  // panel draws it while the reading happens, and a reading that fails still
  // leaves the panel out of whatever it was showing before.
  const messages: HostMessage[] = [{ command: 'setEntry', data: { kind: 'loading' } }]

  const choice = chooseRoot(roots, read)
  if (choice.kind === 'no-folder') {
    messages.push({ command: 'setEntry', data: { kind: 'no-folder' } })
    return { messages, observedRoot: null }
  }

  const { reading, root, ignoredRoots } = choice
  if (reading.kind === 'error') {
    messages.push({
      command: 'setEntry',
      data: { kind: 'error', message: reading.message, root, ignoredRoots },
    })
    return { messages, observedRoot: root }
  }

  messages.push({
    command: 'setProcess',
    data: {
      process: reading.process,
      probe: reading.probe,
      readAt: reading.readAt,
      entry: reading.entry,
      root,
      ignoredRoots,
      inheritedRevision: INHERITED_MODEL_REVISION,
      // The two branches of feature 006 travel beside the others, in the same
      // envelope and in the same order: the sequence is unchanged, and so is
      // the treatment of the error and of the missing folder below.
      decomposition: reading.decomposition,
      history: reading.history,
      // The registry of feature 008 travels beside them, in the same envelope
      // and in the same order: the sequence is unchanged, and so is the
      // treatment of the error and of the missing folder above.
      bugs: reading.bugs,
      // The provenance of feature 007, travelling beside the inherited
      // revision because RF-17 asks for it "like the inherited model".
      extensionVersion: build.version,
      builtFromCommit: build.commit,
      // The greenfield axis of feature 009, appended last, as the contract
      // asks: nothing above it moves, and a panel older than the field ignores
      // what it does not know.
      greenfield: reading.greenfield,
    },
  })
  return { messages, observedRoot: root }
}
